### ISSUE TITLE
上电/重启时有几率通过mqtt上报一个全为0的数据

### ISSUE THREAD

**Issue by happyme531** [a2633063/zM1#32]
RT.
这个问题很影响Home assistant的历史记录曲线显示。
![image](https://user-images.githubusercontent.com/20812356/115119837-06774280-9fdd-11eb-87a8-ccfd4e0aa499.png)

**Comment by happyme531** [comment]
不能指望原作者了，自己动手修一下：
```yaml
  - platform: filter
    name: "zm1 temperature filtered"
    entity_id: sensor.zm1_MACMAC_temperature
    filters:
      - filter: outlier
        window_size: 1
        radius: 12.0
```
